name: build
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v1.0.5
        with:
          compiler: ${{ matrix.dc }}

      - uses: actions/cache@v1
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ hashFiles('**/dub.selections.json') }}
          restore-keys: |
            ${{ runner.os }}-dub-

      - name: Run tests
        run: dub test

      - name: Build
        run: dub build
